Play video in background
ragnor-rs/plugins pull request #2
Opened 2020-10-13 17:10 UTC by VasyaFromRussia

2020-10-21 08:56 UTC, ragnor-rs commented on packages/video_player/video_player/android/src/main/java/io/flutter/plugins/videoplayer/VideoPlayerService.java
> +    private final LongSparseArray<VideoPlayer> videoPlayers = new LongSparseArray<>();
а точно надо было переносить из плагина?
если бы не переносил, то дифф был бы скромнее и совместимее с изменениями из официального плагина

2020-10-21 08:57 UTC, ragnor-rs commented on packages/video_player/video_player/example/android/app/src/main/AndroidManifest.xml
> +    <application
здесь почему такой дифф? табы поменял на пробелы? лучше оставить что было

2020-10-21 08:58 UTC, ragnor-rs commented on packages/video_player/video_player/android/src/main/java/io/flutter/plugins/videoplayer/VideoPlayerPlugin.java
> +    public static void registerWith(io.flutter.plugin.common.PluginRegistry.Registrar registrar) {
порядок методов я бы не менял
это должно идти до VideoPlayerPlugin()

2020-10-21 08:59 UTC, ragnor-rs requested changes
короче, мой консерн главный - минимальная разница с оригинальными исходникам

2020-10-21 09:59 UTC, VasyaFromRussia commented on packages/video_player/video_player/example/android/app/src/main/AndroidManifest.xml
> +    <application
Автоформат просто сделал 🤦 
Надо бы откатить обратно

2020-10-21 10:31 UTC, VasyaFromRussia commented on packages/video_player/video_player/android/src/main/java/io/flutter/plugins/videoplayer/VideoPlayerService.java
> +    private final LongSparseArray<VideoPlayer> videoPlayers = new LongSparseArray<>();
Нам надо делегировать вызовы в VideoPlayer. Как это сделать, оставив videoPlayers на месте? Через Handler?

2020-10-21 12:22 UTC, agovyashov commented on packages/video_player/video_player/android/src/main/java/io/flutter/plugins/videoplayer/PlayerDelegate.java
> +public class PlayerDelegate implements Player {
нельзя было унаследоваться от плеера и переопределить только нужные функции?

2020-10-21 16:09 UTC, ragnor-rs commented on packages/video_player/video_player/example/android/app/src/main/AndroidManifest.xml
> +    <application
надо

2020-10-21 18:02 UTC, VasyaFromRussia commented on packages/video_player/video_player/android/src/main/java/io/flutter/plugins/videoplayer/PlayerDelegate.java
> +public class PlayerDelegate implements Player {
Я решил просто сделать делегат, чтобы не влиять никак на логику работы плеера. Этот делегат только для правильного отображения нотификации нужен.

2020-10-22 09:26 UTC, ragnor-rs approved these changes
very good

2020-10-22 09:30 UTC, ragnor-rs commented on packages/video_player/video_player/android/src/main/java/io/flutter/plugins/videoplayer/VideoPlayerService.java
> +    private final LongSparseArray<VideoPlayer> videoPlayers = new LongSparseArray<>();
сейчас покажу

2020-10-22 09:35 UTC, agovyashov approved these changes

2020-10-22 11:36 UTC, ragnor-rs commented on packages/video_player/video_player/android/src/main/java/io/flutter/plugins/videoplayer/VideoPlayerService.java
> +    private final LongSparseArray<VideoPlayer> videoPlayers = new LongSparseArray<>();
глянь https://github.com/ragnor-rs/plugins/pull/6

2020-10-22 14:27 UTC, ragnor-rs requested changes
договорились оставить видео плееры в плагине

2020-10-22 14:27 UTC, VasyaFromRussia commented on packages/video_player/video_player/android/src/main/java/io/flutter/plugins/videoplayer/VideoPlayerService.java
> +    public static final int PLAYER_NOTIFICATION_ID = 1;
Сделать через ресурсы

2020-10-29 12:10 UTC, VasyaFromRussia commented
@ragnor-rs оставил startForeground в onStartCommand, а всю инициализацию вытащил в onCreate сервиса. Общение интентами делать не стал, потому что в сервис всё равно надо передавать плеер, так что байндинг нужен, а через него проще

2020-10-29 12:26 UTC, merged